export const fieldHelper = {
  id: "ID",
  uid: "User ID",
  first_name: "Имя",
  last_name: "Фамилия",
  second_name: "Отчество",
  middle_name: "Отчество",
  full_name: "ФИО",
  fullname: "ФИО",
  username: "Имя пользователя",
  gender: "Пол",
  sex: "Пол",
  age: "Возраст",
  title: "Заголовок",
  description: "Описание",
  name: "Имя",
  seller_name: "Имя",
  birth_date: "Дата рождения",
  birthday: "Дата рождения",
  bdate: "Дата рождения",
  last_seen: "Был в сети",
  verified: "Подтвержден",
  category: "Категория",
  hostname: "Hostname",
  location: "Местоположение",
  location_name: "Местоположение",
  main_city: "Город",
  region: "Регион",
  address: "Адрес",
  university_name: "Университет",
  screen_name: "Отображаемое имя",
  registered: "Зарегистрирован",
  instagram: "Instagram",
  github_username: "GitHub",
  twitter: "Twitter",
  twitter_username: "Twitter",
  facebook: "Facebook",
  facebook_username: "Facebook",
  facebook_id: "Facebook",
  facebook_name: "Facebook Name",
  skype: "Skype",
  linkedin_username: "Linkedin",
  vk: "ВК",
  livejournal: "LiveJournal",
  home_town: "Родной город",
  followers_count: "Подписчики",
  about: "О себе",
  games: "Игры",
  activity: "Деятельность",
  comment: "Комментарий",
  user_ip: "IP",
  mobile_phone: "Мобильный",
  work_phone: "Рабочий",
  home_phone: "Домашний",
  work: "Работа",
  counterparty_phone: "Контрагент",
  tel: "Телефон",
  phone: "Телефон",
  phone_operator: "Оператор",
  phone_other: "Доп. телефон",
  other_contact: "Доп. телефон",
  contact_phone: "Контакт. номер",
  number: "Номер",
  seller_phone: "Телефон",
  phones: "Телефоны",
  phone_numbers: "Номера",
  email: "Email",
  user_email: "Почта",
  works_email: "Рабочая почта",
  profession: "Профессия",
  education: "Образование",
  information: "Информация",
  career: "Карьера",
  study: "Образование",
  photo_url: "Фото",
  profile_url: "Профиль",
  actual_phone_date: "Актуальность номера",
  car_brand: "Марка авто",
  car_number: "Номер авто",
  color: "Цвет",
  date: "Дата",
  fname: "Полное имя",
  nickname: "Ник",
  wo: "Был в сети",
  password: "Пароль",
  status: "Статус",
  bank_name: "Банк",
  job_title: "Job Title",
  job_title_role: "Job Title Role",
  job_company_id: "Job Company ID",
  job_company_name: "Job Company Name",
  job_company_website: "Job Company Site",
  company_id: "Company ID",
  company_name_native: "Компания",
  company_name: "Компания",
  "company_name_i@nternat": "Компания (International)",
  address_line1: "Address Line 1",
  address_line2: "Address Line 2",
  address_line3: "Address Line 3",
  address_line4: "Address Line 4",
  country_code: "Код страны",
  country_name: "Страна",
  website: "Сайт",
  revenue: "Доход",
  total_assets: "Общие активы",
  interests: "Интересы",
  skills: "Навыки",
  languages: "Языки",
  numbuster_array: "Numbuster",
  getcontact_array: "GetContact",
  pickup_point: "Пункт выдачи",
  subdivision_code: "Подразделение",
  pickup_point_code: "Подразделение",
  yauid: "Яндекс ID",
  position: "Позиция",
  value: "Наименование компании",
  inn: "ИНН",
  kpp: "КПП",
  ogrn: "ОГРН",
  ogrn_date: "Дата ОГРН",
  okved: "Код ОКВЭД",
  type: "Тип",
  branch_type: "Тип филиала",
  branch_count: "Количество филиалов",
  full_with_opf: "Полное наименование",
  short_with_opf: "Кратное наименование",
  employee_count: "Кол-во работников",
  emails: "Электронные адреса",
  opf_type: "версия справочника",
  opf_code: "код ОКОПФ",
  opf_full: "полное название ОПФ",
  opf_short: "краткое название ОПФ",
  state_status: "Статус организации",
  state_actuality_date: "дата последних изменений",
  state_registration_date: "дата регистрации",
  state_liquidation_date: "дата ликвидации",
  management_name: "Руководитель",
  management_post: "должность руководителя",
  address_postal_code: "Индекс",
  postal: "Индекс",
  address_source: "Полный адрес",
  country: "Страна",
  address_geo_lat: "Широта",
  address_geo_lon: "Долгота",
  reminded_call_at: "Напомнить о звонке в",
  cash: "Деньги",
  work_country: "Страна работы",
  company: "Компания",
  groupType: "Тип группы",
  OrderStatus: "Статус заказа",
  chats: "Чаты",
  shipping_lastname: "Фамилия при заказе",
  sick_leave: "Выздоровление",
  data: "Данные",
  source: "Источник",
  points: "Точки",
  profiles: "Профили",
  site: "Сайт",
  personal_fax: "Факс",
  notify_login_new_ip: "Уведомлять о входе с новых IP",
  subcategory: "Подкатегория",
  time_to_delivery_max: "Максимальное время ожидания",
  createdDateTime: "Создано",
  last_ip: "IP",
  logged_ip: "IP",
  street_addresses: "Улица",
  payment_company: "Компания платежа",
  Ip: "IP",
  card: "Карта",
  cards: "Карты",
  firstname: "Имя",
  breast_size: "Размер груди",
  reg_time: "Дата регистрации",
  additional_contact: "Дополнительный контакт",
  business_trip: "Бизнес путешествие",
  payment_zone: "Зона платежа",
  bookmark: "Закладка",
  processing_type: "Тип обработки",
  taken_at: "Принято в",
  city: "Город",
  timezone: "Часовой пояс",
  last_login: "Последний заход",
  modified_timestamp: "Временная метка",
  isForbiddenToCall: "Запрещено звонить",
  personal_gender: "Пол",
  passport_given_by: "Паспорт выдан",
  Amount: "Сумма",
  note: "Заметка",
  register_date: "Дата регистрации",
  payment_city: "Город оплаты",
  left_requests: "Оставшиеся запросы",
  clothing_size: "Размер одежды",
  coordinates: "Координаты",
  short: "Краткий адрес",
  yaid: "YandexID",
  korpus: "Корпус",
  delivered_at: "Доставлено",
  salt: "Соль пароля",
  actual_address: "Текущий адрес",
  pre_delivery_time: "Ожидаемое время доставки",
  snils: "СНИЛС",
  approvalCode: "Код подтверждения",
  prefix: "Префикс",
  modified_at: "Изменено",
  total_earning: "Всего заработано",
  lastserver: "Последний сервер",
  telephoneNumber: "Телефон",
  metro: "Метро",
  lastUse: "Последнее использование",
  vacation: "Отпуск",
  app: "Приложение",
  last_activity: "Последняя активность",
  email2: "Другая почта",
  land: "Страна",
  contact_person: "Контакт",
  last_login_at: "Последний заход",
  date_lastact: "Последняя активация",
  sound_notification: "Звуковое уведомление",
  currency: "Валюта",
  result: "Результат",
  lastdate: "Время",
  shop_address: "Адрес магазина",
  account_owner: "Владелец",
  isVip: "ВИП",
  ErrorCode: "Код ошибки",
  createdAt: "Создано",
  user_id: "User ID",
  created_at: "Создано",
  hair_color: "Цвет волос",
  nationality: "Национальность",
  activity_type: "Тип активности",
  members_count: "Количество участников",
  device_id: "ID устройства",
  test: "Тест",
  addStatus: "Статус добавления",
  account: "Аккаунт",
  last_modified_date: "Дата изменения",
  online: "Онлайн",
  personal_city: "Город",
  ok_id: "OK ID",
  text: "Текст",
  sync_status: "Статус синхронизации",
  hr_business_partner: "Бизнес партнер",
  creation_time: "Дата создания",
  forum_time: "Время на форуме",
  lastActivityAt: "Последняя активность",
  groupId: "ID группы",
  notify_sms: "Уведомление СМС",
  userPrincipalName: "Имя пользователя",
  address_full: "Адрес",
  place_confirmed_at: "Место подтверждено",
  sys_number: "Системный номер",
  has_mobile: "Есть телефон",
  tags: "Тэги",
  checks_left: "Проверок осталось",
  header: "Заголовок",
  allowed_ip: "Разрешенные IP",
  personal_notes: "Личные заметки",
  password_version: "Тип пароля",
  brand: "Марка",
  personal_birthdate: "Дата рождения",
  session: "Сессия",
  doorcode: "Домофон",
  sort_priority: "Приоритет сортировки",
  region_name: "Регион",
  number_orders: "Кол-во заказов",
  books: "Книги",
  forum_warn: "Предупреждения",
  restricted_days: "Дней ограничения",
  Pan: "Номер карты",
  custom_title: "Другое название",
  payment_status: "Статус платежа",
  code: "Код",
  password_sha1: "Пароль в SHA1",
  passport_number: "Паспорт",
  reminded_at: "Напомнено",
  sms_id: "ID СМС",
  lawyer: "Юрист",
  card_number: "Номер карты",
  manager: "Менеджер",
  login_ip: "IP",
  amount_blocked: "Замороженная сумма",
  version: "Версия",
  isBlocked: "Заблокирован",
  signature: "Подпись",
  regions: "Регионы",
  language_id: "ID языка",
  work_fax: "Рабочий факс",
  pref_schedule: "Предпочитаемый график",
  personal_mailbox: "Личный Email",
  action: "Действие",
  created: "Создано",
  citizenship: "Гражданство",
  car: "Машина",
  amount_charged: "Сумма пополнения",
  league: "Лига",
  lang: "Язык",
  amount: "Сумма",
  forum_post: "Пост",
  body_type: "Тип заголовка",
  address_building: "Адрес здания",
  date_registered: "Дата регистрации",
  name_document: "Название документа",
  address_place: "Адрес",
  lastname: "Фамилия",
  confirmed: "Подтвержден",
  personal_street: "Улица",
  favorite_game: "Любимая игра",
  delivery_price: "Цена доставки",
  payment_lastname: "Фамилия",
  vk_id: "VK ID",
  date_added: "Дата добавления",
  startTime: "Время начала",
  coords: "Координаты",
  num_followers: "Кол-во подписчиков",
  graduation: "Выпускной",
  groupName: "Группа",
  fully_payed: "Оплата полностью",
  shipping_firstname: "Имя",
  moderationStatus: "Статус модерирования",
  floor: "Этаж",
  contract_number: "Телефон",
  isApproved: "Подтвержден",
  sdacha: "Сдача",
  number_of_payments: "Кол-во платежей",
  is_phone_confirmed: "Телефон подтвержден",
  location_latitude: "Широта",
  subscribe_sms: "Подписка СМС",
  spy_subscription: "Подписка на слежение",
  termination: "Завершение",
  works: "Работа",
  cashback_balance: "Кэшбэк",
  depositAmount: "Депозит",
  avg_sum: "Средняя сумма",
  tokens: "Токены",
  office: "Офис",
  jurisdiction: "Юрисдикция",
  votes: "Голоса",
  pref_salary: "Предпочитаемая зарплата",
  province: "Область",
  faculty: "Факультет",
  timestamp: "Время",
  started_at: "Начато в",
  city_name: "Город",
  experience: "Опыт",
  login_attempts: "Попытки входа",
  born_location: "Место рождения",
  work_mailbox: "Рабочий Email",
  flat: "Квартира",
  work_logo: "Логотип работы",
  given_date: "Дата выдачи",
  shoe_size: "Размер обуви",
  tariff: "Тариф",
  work_street: "Улица работы",
  num_following: "Количество подписчиков",
  last_activity_date: "Последняя активность",
  register_ip: "IP регистрации",
  fb_name: "Имя Facebook",
  number_document: "Номер документа",
  task_completed: "Работа завершена",
  amount_of_payments: "Сумма платежей",
  date_termination: "Дата завершения",
  give_reason: "Причина выдачи",
  mail: "Почта",
  bot: "Бот",
  additional_info: "Дополнительная информация",
  time: "Время",
  cardholderName: "Имя держателя карты",
  vklastid: "ID ВКонтакте",
  total_sum: "Сумма в целом",
  profit: "Профит",
  index: "Индекс",
  user_agent: "User-Agent",
  user_language: "Язык пользователя",
  isSupervisor: "Супервайзер",
  isBot: "Бот",
  birth_year: "Год рождения",
  insta_id: "ID Instagram",
  index_house: "Индекс дома",
  job: "Работа",
  "user-agent": "UserAgent",
  actual_amount: "Текущая сумма",
  admin: "Админ",
  products: "Продукты",
  birthplace: "Место рождения",
  reg_date: "Дата регистрации",
  favorites: "Любимое",
  stored_hash: "Хэш",
  login: "Логин",
  time_created: "Время создания",
  date_document: "Дата документа",
  banned: "Заблокирован",
  total_paid: "Уже выплачено",
  creation_date: "Дата создания",
  payment_firstname: "Имя",
  timestamp_x: "Время",
  house: "Дом",
  isPreauth: "Предварительная проверка",
  authCode: "Код авторизации",
  time_to_delivery: "Время доставки",
  score: "Счет",
  sum: "Сумма",
  image: "Изображение",
  passport_issued_by: "Паспорт выдан",
  active: "Активен",
  payment_service: "Сервис оплаты",
  yandex_id: "YandexID",
  passport_date: "Дата паспорта",
  uri: "Ссылка",
  names: "Имена",
  time_to_delivery_min: "Минимальное время доставки",
  payment_method: "Метод оплаты",
  purse: "Кошелек",
  license: "Лицензия",
  foto: "Фото",
  personal_birthday: "День рождения",
  clothes_size: "Размер одежды",
  user_address_id: "ID адреса",
  site_header: "Заголовок сайта",
  ipCountry: "Страна IP",
  document: "Документ",
  issued: "Выдан",
  orderSum: "Сумма заказа",
  lastlogin: "Последний заход",
  director: "Директор",
  link: "Ссылка",
  remote_work: "Удаленная работа",
  coupon: "Купон",
  platform: "Платформа",
  vip: "ВИП",
  street: "Улица",
  tv: "Телевизор",
  personal_photo: "Личное фото",
  update_date: "Дата изменения",
  average_payment: "Средний платеж",
  shiping_address_1: "Другой адрес доставки",
  apartament: "Жилье",
  tattoo: "Тату",
  streetAddress: "Улица",
  url: "Ссылка",
  yandex_uid: "YandexID",
  work_city: "Город работы",
  weight: "Вес",
  location_longitude: "Широта",
  firstName: "Имя",
  personal_country: "Страна",
  paymentType: "Тип платежа",
  lastName: "Фамилия",
  display_name: "Отображаемое имя",
  spam_count: "Счетчик спама",
  confirm_code: "Код подтверждения",
  isDeleted: "Удалено",
  date_birthplace: "Дата рождения",
  biography: "Биография",
  piercing: "Пирсинг",
  phone_date: "Дата телефона",
  amount_client_paid: "Выплаченная сумма",
  updated_on: "Обновлено",
  bday: "Дата рождения",
  payment_address_2: "Другой адрес платежа",
  ips: "Список IP",
  account_name: "Имя аккаунта",
  countries: "Страны",
  operator: "Оператор",
  discount_card_verified: "Карта подтверждена",
  state: "Состояние",
  role: "Роль",
  time_limit: "Лимит времени",
  total_payments: "Всего платежей",
  personal_mobile: "Личный телефон",
  photo_max_orig: "Фото",
  photo_max: "Фото",
  scam: "Скам",
  yataxi_id: "YaTaxi ID",
  vendor: "Производитель",
  work_position: "Должность работы",
  passport: "Паспорт",
  sms_price: "Цена за СМС",
  payment_address_1: "Другой адрес оплаты",
  request: "Запрос",
  pub_date: "Дата публикации",
  payment_address: "Адрес оплаты",
  heightй: "Рост",
  surname: "Фамилия",
  date_register: "Дата регистрации",
  movies: "Фильмы",
  info: "Информация",
  patronymic: "Отчество",
  deactivated: "Удален",
  time_zone: "Временная зона",
  balance: "Баланс",
  area: "Область",
  cathegory: "Категория",
  restricted: "Запрещено",
  remind_at: "Напомнить",
  Location: "Геолокация",
  decree: "Декрет",
  anonim_payment: "Анонимный платеж",
  given_by: "Выдан",
  summa: "Сумма",
  price: "Цена",
  language: "Язык",
  date_order: "Дата заказа",
  vk_name: "Имя ВКонтакте",
  locale: "Локализация",
  phone_number: "Телефон",
  fb_id: "Facebook ID",
  shoes_size: "Размер обуви",
  members: "Участники",
  comments: "Комментарии",
  ErrorMessage: "Сообщение ошибки",
  carrier: "Работа",
  name_license: "Название лицензии",
  OrderNumber: "Номер заказа",
  password_md5: "MD5 пароля",
  birthdate: "Дата рождения",
  hash: "Хэш",
  shipping_address_2: "Другой адрес доставки",
  breast: "Грудь",
  created_on: "Создан",
  entrance: "Подъезд",
  reliable: "Адрес активен",
  courier_id: "ID курьера",
  adopted_by_courier: "Принято курьером",
  adopted_by_courier_at: "Принято курьером в",
  courier_arrived_to_place_at: "Курьер прибыл на место в",
  courier_assigned_at: "Курьер назначен в",
  arrived_to_customer_at: "Прибыл к заказчику в",
  moved_to_delivery_at: "Переведен в доставку в",
  call_center_confirmed_at: "Звонок подтвержден в",
  restaurant_received_at: "Ресторан получил в",
  updated_at: "Обновлено в",
  cart_id: "ID корзины",
  place_id: "ID места",
  finished_at: "Завершено в",
  flow_type: "Тип потока",
  phone_change_time: "Время изменения телефона",
  order_nr: "Номер заказа",
  university: "Университет",
  lat: "Широта",
  lng: "Долгота",
  time_zone_offset: "Смещение timezone",
  checkword_time: "Время подтверждения пароля",
  admin_notes: "Записи админа",
  room: "Комната",
  ip: "IP",
  incident: "Проишествие",
  born_place: "Место рождения",
  previous_conviction: "Предыдущая судимость",
  last_visit: "Последнее посещение",
  latitude: "Широта",
  longitude: "Долгота",
  mailru_id: "ID Mail.ru",
  transaction_type: "Тип операции",
  license_number: "Госномер",
  old_license_plate: "Старый госномер",
  manufacture_year: "Год выпуска",
  engine_size: "Объем двигателя",
  HP_power: "Мощность л.с.",
  PTS: "ПТС",
  SVehicle: "СТС",
  carcass_number: "№ кузова",
  chassis_number: "№ шасси",
  engine_number: "№ двигателя",
  VIN: "VIN",
  additional_information: "Дополнительная информация",
  Type_of_base: "Тип базы",
  registration_sign: "Рег знак",
  old_registration_sign: "Прежний регистрационный знак",
  operation: "Операция",
  date_of_operation: "Дата операции",
  condition: "Состояние",
  model: "Модель",
  year_of_issue: "Год выпуска",
  vin: "VIN",
  engine: "Двигатель",
  chassis: "Шасси",
  body: "Кузов",
  engine_power_l_s: "Мощность двиг л с",
  engine_power_kw: "Мощность двиг КВт",
  engine_model: "Модель двиг",
  vehicle_passport: "Паспорт ТС",
  vehicle_passport_date: "Дата паспорта ТС",
  svideteregistration_authority: "Свидетельство о регистрации",
  date_of_registration_certificate: "Дата свидетельствa о регистрации",
  representation: "Предст док",
  n_representation: "N предст док",
  date_of_representation: "Дата предст док",
  by_whom_the_representation_was_issued_doc: "Кем выдан предст док",
  insurance_policy: "Страховой полис",
  date_of_issue_of_the_insurance_policy: "Дата выдачи страхового полиса",
  where_the_policy_was_issued: "Кем выдан полис",
  cost: "Стоимость",
  type_of_unit: "Свид на агрегат",
  color_group: "Группа цвета",
  supplydivision: "Подразделение",
  document_type: "Тип документа",
  document_id_passport: "Док удост лич пасп",
  address1: "АДРЕС",
  place_of_work: "Место работы",
  enterprise_codeiyatiya: "Код предприятия",
  enterprise_tin: "ИНН предприятия",
  enterprise_ogrn: "ОГРН предприятия",
  enterprise_checkpoint: "КПП предприятия",
  address_of_corp: "АДРЕС",
  enterprise_phone_number: "Телефон предприятия",
  date_registration_of_a_legal_entity: "Дата регистрации юридического лица",
  full_name_of_the_trustee: "ФИО Доверенного лица",
  date_of_birth_of_trustee: "Дата рожд дов лица",
  address_of_trustee: "Адрес дов лица",
  registered_in_the_subdivision: "На учете в подразделении",
  type_of_bodyva: "Тип кузова",
  special_sign: "Специальный знак",
  special_designation: "Спецназначение",
  tin_of_an_individual: "ИНН Физического лица",
  country_of_import: "Страна импорта",
  primary_title_deed: "Первичный ПТС",
  issued_by_the_title_deed: "Кем выдан ПТС",
  maximum_permitted_weight: "Максимально разрешенная масса",
  unladen_weight: "Масса без нагрузки",
  region_of_registration: "Район регистрации",
  date_of_first_registration: "Дата первичной регистрации",
  special_marks: "Особые отметки",
  employee_mail: "Почта сотрудника",
  create_date: "Дата создания",
  last_date: "Был в сети",
  date_reg: "Дата регистрации",
  zipcode: "Почтовый индекс",
  delivery_address: "Адрес доставки",
  delivery_city: "Город доставки",
  delivery_coutry: "Страна доставки",
  algorithm: "Алгоритм",
  firsttotalcost: "Конечная цена",
  status_detail: "Подробности статуса",
  comment_1c: "Комментарий 1С",
  marital_status: "Семейный статус",
  last_message_at: "Последнее сообщение в",
  nick: "Ник",
  faculty_name: "Факультет",
  education_form: "Форма обучения",
  education_status: "Статус обучения",
  referrer_by: "Пригласил",
  referrals_count: "Кол-во рефералов",
  clicks_count: "Кол-во кликов",
  device: "Устройство",
  os: "Операционная система",
  network: "Сеть",
  service_name: "Название сервиса",
  service_data: "Данные сервиса",
  dob: "Дата рождения",
  department: "Отделение",
  contract_num: "Номер договора",
  designation: "Название",
  work_time: "Время работы",
  keyword: "Ключевое слово",
  section: "Раздел",
  subsection: "Подраздел",
  heading: "Рубрика",
  lon: "Долгота",
  org: "Провайдер",
  loc: "Координаты",
  seller: "Продавец",
  parameters: "Параметры",
  pictures: "Картинки",
  crime_init_date: "Дата возбуждения уголовного дела",
  new_uk_number: "Новая статья УК",
  old_uk_number: "Старая статья УК",
  new_uk_info: "Содержание по новому УК",
  old_uk_info: "Содержание по сторому УК",
  document_number: "Номер документа",
  document_serie: "Серия документа",
  docCountry: "Страна документа",
  work_place: "Рабочее Место",
  contact_email: "Контактный Email",
  sndr_acnt_ccode: "Код Валюты Аккаунта Отправителя",
  client_type_id: "ID Типа Клиента",
  inviter_id: "ID Приглашающего",
  serie: "Серия",
  lpu_code: "Код ЛПУ",
  ident_num: "Номер идентификации",
  type_of_operation: "Тип операции",
  referer_id: "ID Реферера",
  given_place: "Данное место",
  conversations_unread: "Непрочитанные диалоги",
  shipping_country_id: "Страна доставки",
  vu_num: "Номер ВУ",
  was_deposited: "Депонировано",
  fbid: "ID Facebook",
  user_name: "Имя пользователя",
  card_type: "Тип карты",
  race: "Раса",
  settlement_accept_name: "Название приемной поселения",
  all_jumps: "Все прыжки",
  is_banned: "Забанен",
  LastSessionDay: "Последний день сессии",
  custombonusper: "Персональный бонус",
  brand_name_licensee: "Лицензиат названия бренда",
  forum_update: "Обновление форума",
  contact_post: "Почтовый контакт",
  company_scale_code: "Код масштаба компании",
  personal_state: "Персональное состояние",
  insurance_type: "Тип страхования",
  icq: "ICQ",
  buh_phone: "Телефон бухгалтерии",
  medical_company: "Медицинская компания",
  serie_number: "Номер и серия",
  booked_at: "Забронировано",
  reput_plus: "Репутация плюс",
  town: "Город",
  address_comment: "Комментарий адреса",
  "counters.hits": "Хиты счетчиков",
  post: "Почта",
  addr_stroen: "Адрес магазина",
  login_time: "Время входа",
  ib_scheme_id: "ID Схемы IB",
  xml_id: "XML ID",
  pasport_serie: "Серия паспорта",
  passport_serie: "Серия паспорта",
  register_doc_serie: "Серия регистрационных документов",
  joinStatus: "Статус присоединения",
  want_receive_info: "Хотите получать информацию",
  aim: "Цель",
  change_phone_verify: "Подтвердить изменение телефона",
  favourites_count: "Количество избранных",
  flag_pep: "Флаг PEP",
  middlename: "Отчество",
  relocity_invoice_attachments: "Вложения счета-фактуры",
  phone_2: "Дополнительный телефон",
  correspondent_account: "Корреспондентский счет",
  organization: "Организация",
  visa_price_stored: "Сохраненная цена визы",
  inn_ccode: "Код ИНН",
  shipping_company: "Компания доставки",
  prev_PTS: "Предыдущий PTS",
  last_time_star: "Последняя звезда",
  linkedin: "LinkedIn",
  startTimeLocal: "Локальное время начала",
  id_courier: "ID Курьера",
  buildinfo: "Информация о здании",
  postalCode: "Почтовый код",
  notes: "Заметки",
  telegram: "Telegram",
  place_of_birth: "Место рождения",
  raion: "Район",
  date_delivered: "Дата доставки",
  addr_ron: "Адрес (РОН)",
  LastOpenDate: "Последняя дата открытия",
  height: "Высота",
  digitalf22activate: "Активация Digitalf22",
  marital: "Семейный статус",
  agr_id: "ID Договора",
  sv_reg: "SV Регистрация",
  date_prev_PTS: "Дата предыдущего PTS",
  shipping_country: "Страна доставки",
  realname: "Настоящее имя",
  client_id: "ID Клиента",
  shipping_center: "Центр доставки",
  latesteventbooking: "Последнее бронирование события",
  passport_expires_on: "Срок действия паспорта",
  inserted: "Вставлено",
  payment_type: "Тип оплаты",
  unsubscribed_at: "Отписано в",
  unverified_email: "Неподтвержденный Email",
  document_data: "Данные Документа",
  utm_keyword: "UTM Ключевое Слово",
  ban_reason: "Причина бана",
  data_anonymized: "Анонимизированные данные",
  payment_country: "Страна платежа",
  profile_link: "Ссылка на профиль",
  index_to_ccode: "Индекс к коду страны",
  confirmation_sent_at: "Подтверждение отправлено в",
  last_four: "Последние четыре",
  "twitter.nickName": "Twitter. Никнейм",
  f_office: "F офис",
  projectId: "ID проекта",
  registration_date: "Дата регистрации",
  posts: "Сообщения",
  docnumber: "Номер документа",
  unrestricted_value: "Неограниченное значение",
  document_full: "Полный документ",
  address2: "Адрес 2",
  was_not_confirmed: "Не подтверждено",
  deleted: "Удалено",
  u_office: "U офис",
  stat_price: "Статистическая цена",
  have_kids: "Есть дети",
  bday_day: "День рождения",
  date_rejected: "Дата отклонена",
  failed_logins: "Неудачные входы",
  social_id: "Социальный ID",
  "vkontakte.imgUrl": "URL изображения во ВКонтакте",
  place_type: "Тип места",
  encrypted_password: "Зашифрованный пароль",
  tokensPaid: "Оплаченные токены",
  importance_deg: "Степень важности",
  relocity_destination_city: "Город назначения Relocity",
  Firstname: "Имя",
  current_sign_in_ip: "IP-адрес текущей входа",
  currency_code: "Код валюты",
  wo_sms: "Без SMS",
  userType: "Тип пользователя",
  like_count: "Количество лайков",
  is_active: "Активен",
  date_inc: "Дата внесения",
  relocity_comments: "Комментарии связанные со скоростью",
  engagement_explain: "Объяснение вовлеченности",
  crime_type: "Тип преступления",
  uuid: "UUID",
  work_additionally: "Дополнительная работа",
  form: "Форма",
  loyalty_card: "Карта лояльности",
  reg: "Регистрация",
  number_duplicate: "Номер дубликата",
  nas_punkt: "Населенный пункт",
  schedule: "Расписание",
  accept_language: "Принятый язык",
  relocity_agreement_attachments: "Вложения соглашения связанные со скоростью",
  tech_passport: "Технический паспорт",
  address_name: "Название адреса",
  relocity_type: "Тип скорости",
  is_certificate: "Является сертификатом",
  delivery_type: "Тип доставки",
  pasport_number: "Номер паспорта",
  shipping_city: "Город доставки",
  doverennost: "Доверенность",
  zip: "ZIP",
  regdate: "Дата регистрации",
  price_wo_disc: "Цена без скидки",
  polis_given_date: "Дата выдачи полиса",
  relocitymovedate: "Дата перемещения со скоростью",
  f_index: "Индекс",
  organisation: "Организация",
  kod_org: "Код организации",
  xfields: "X-поля",
  default_profile_image: "Изображение профиля по умолчанию",
  payment: "Оплата",
  contact_id: "ID контакта",
  building: "Здание",
  is_translator: "Является переводчиком",
  email_confirmed: "Электронная почта подтверждена",
  RegistrationDate: "Дата регистрации",
  friends_count: "Количество друзей",
  verify_code: "Код подтверждения",
  members_display_name: "Отображаемое имя участника",
  details: "Детали",
  nation: "Нация",
  fraudsterList: "Список мошенников",
  personal_zip: "Персональный ZIP",
  bio: "Биография",
  expire_month: "Месяц истечения",
  user_info: "Информация о пользователе",
  paypal_email: "Электронная почта PayPal",
  "counters.likes": "Лайки",
  fullfamily: "Полная семья",
  date_duplicate: "Дата дубликата",
  twitterid: "ID Twitter",
  google_email: "Электронная почта Google",
  number_bookings_ever: "Количество бронирований",
  staff_dat_out: "Дата выхода персонала",
  last_sign_in_ip: "IP последней авторизации",
  favorite_time: "Любимое время",
  email_old: "Старый email",
  password1: "Пароль 1",
  medical_insurance: "Медицинская страховка",
  debtor: "Должник",
  user_state: "Статус пользователя",
  guaranty_letter_sent: "Гарантийное письмо отправлено",
  wo_phone: "Без телефона",
  settlement_account: "Расчетный счет",
  signup_date: "Дата регистрации",
  new_msg: "Новое сообщение",
  places_number: "Количество мест",
  address_additionally: "Дополнительный адрес",
  public_phone: "Общественный телефон",
  legal_form_code: "Код юридической формы",
  comm_num: "Коммерческий номер",
  certifications: "Сертификаты",
  flag_abox: "Флаг A-box",
  rozysk_stopped: "Розыск остановлен",
  fullname_ua: "Полное имя UA",
  engagement_score_last_month: "Оценка вовлеченности в прошлом месяце",
  vkid: "VK ID",
  utm_term: "UTM термин",
  limit: "Лимит",
  homepage: "Домашняя страница",
  last_post: "Последний пост",
  vip_post: "VIP пост",
  archived: "Архивировано",
  samyragon: "Samyragon",
  countrycode: "Код страны",
  engagement_explain_last_month: "Объяснение вовлеченности в прошлом месяце",
  rcpn_name: "Имя RCPN",
  google_id: "ID Google",
  abbreviated_name_licensee: "Сокращенное название лицензиата",
  byname: "По имени",
  pensionnoe: "Пенсионное",
  buh_fio: "ФИО бухгалтера",
  director_name: "Имя директора",
  bitcoin: "Bitcoin",
  old_username: "Старый имя пользователя",
  warning_points: "Очки предупреждения",
  engine_no: "Номер двигателя",
  wo_email: "Без email",
  shipping_method: "Способ доставки",
  personsUpdatedAt: "Дата обновления персональных данных",
  year: "Год",
  house_corpus_flat: "Дом/корпус/квартира",
  gpg: "GPG",
  udost: "Удостоврение",
  operator_payments_managed: "Управление платежами оператора",
  sts: "STS",
  forum_reputation: "Репутация на форуме",
  business_name: "Название бизнеса",
  track_number: "Номер отслеживания",
  dateCreated: "Дата создания",
  cmdLine: "CmdLine",
  polis_end_date: "Дата окончания полиса",
  date_create: "Дата создания",
  inferred: "Выводимый",
  is_pollable: "IsPollable",
  pozyvnoi: "Pozyvnoi",
  agent: "Агент",
  ip_state: "IP статус",
  icq_num: "ICQ номер",
  referal: "Реферал",
  warnCount: "Количество предупреждений",
  docserie: "Серия документа",
  msg_total: "Общее количество сообщений",
  engagement_score: "Рейтинг вовлеченности",
  personal_data_processing_accepted: "Принято обработку персональных данных",
  documentseries: "Серия документов",
  gravatar: "Gravatar",
  arrears: "Задолженность",
  commercial_director: "Коммерческий директор",
  lang_code: "Код языка",
  issueauthority: "Орган, выдающий документ",
  unit: "Единица",
  updated: "Обновлено",
  home_address: "Домашний адрес",
  "counters.comments": "Количество комментариев",
  password2: "Пароль 2",
  points_vote: "Голоса за очки",
  ip_info: "Информация об IP-адресе",
  have_spouse: "Есть супруг(а)",
  phone_confirmed_at: "Телефон подтвержден в",
  address_real: "Реальный адрес",
  passport_code: "Код паспорта",
  is_auto_registered: "Автоматически зарегистрирован",
  has_photo: "Есть фото",
  groupUrl: "URL группы",
  date_modify: "Дата изменения",
  payment_country_id: "ID страны платежа",
  activity_visible: "Видимость активности",
  aboxactivate: "Aboxactivate",
  partner_data: "Данные партнера",
  bonuses_granted: "Предоставленные бонусы",
  origin: "Источник",
  friend_status: "Статус друга",
  public_email: "Публичный email",
  balance_currency: "Валюта баланса",
  driver_license: "Водительское удостоверение",
  joined: "Присоединился",
  base_sum: "Основная сумма",
  referurl: "Referurl",
  macroregion_to_ncode: "Макрорегион к ncode",
  business_type: "Тип бизнеса",
  hasCoverPhoto: "Есть обложка фото",
  last_location: "Последнее местоположение",
  restricted_date: "Дата ограничения",
  single_visa_price: "Цена одиночной визы",
  facebook_imgUrl: "URL изображения на Facebook",
  address_fact: "Фактический адрес",
  additionally: "Дополнительно",
  sndr_name: "Имя отправителя",
  mindbox_updated_at: "Mindbox обновлен в",
  payerSum: "Сумма плательщика",
  first_user_interaction: "Первое взаимодействие с пользователем",
  advcake_url: "URL Advcake",
  last_sign_in_at: "Последний вход в",
  post_passport_pb: "Почтовый паспорт ПБ",
  passport_prefix: "Префикс паспорта",
  contact_fio: "ФИО контакта",
  tag_id: "ID тега",
  flag_digitalf22: "Флаг Digitalf22",
  update_batch_no: "Номер пакета обновления",
  ok: "OK",
  had_completed_orders_before: "Были завершенные заказы ранее",
  company_name_internat: "Интернациональное название компании",
  last_invited_date: "Дата последнего приглашения",
  actual_region: "Текущий регион",
  speciality: "Специальность",
  post_passport_bc: "Почтовый паспорт БЦ",
  year_of_application: "Год подачи заявления",
  dat_recognize: "Дата распознания",
  rozysk_info: "Информация для розыска",
  msn: "MSN",
  waystatus_ccode: "Статус маршрута в коде",
  taxi_status: "Статус такси",
  prxcityads: "PrxCityAds",
  display_style_group_id: "ID группы стиля отображения",
  favorite_day: "Любимый день",
  card_holder: "Держатель карты",
  real_ip: "Реальный IP-адрес",
  isRemoteWork: "Удаленная работа",
  personal_pager: "Личный пейджер",
  payment_deadline: "Срок оплаты",
  bank: "Банк",
  allow_mail: "Разрешить почту",
  last_selected_payment_type: "Последний выбранный тип оплаты",
  insured: "Застрахованный",
  passport_issuer: "Выдающий паспорт",
  contactsCount: "Количество контактов",
  fax: "Факс",
  gps_n: "GPS N",
  information_suspension_resumption:
    "Информация о приостановлении/возобновлении",
  lid: "LID",
  deleted_at: "Удалено в",
  issueAuthority: "Выдающий орган",
  addr_kv: "Адрес KV",
  stars_num: "Количество звезд",
  nds_number2: "Номер НДС 2",
  work_notes: "Рабочие заметки",
  forum_read: "Чтение форума",
  pid: "PID",
  polis_number: "Номер полиса",
  rpobarcode_ccode: "Код RPOBarcode",
  soc_links: "Социальные ссылки",
  relocity_overall_progress_attachments: "Общий прогресс Relocity с вложениями",
  carcass: "Каркас",
  domain: "Домен",
  _id: "ID",
  last_modified: "Последнее изменение",
  sign_in_count: "Количество входов",
  reason: "Причина",
  dateIssue: "Дата выдачи",
  soato_decode: "Декодирование SOATO",
  blocked: "Заблокирован",
  organization_name: "Название организации",
  current_sign_in_at: "Текущее время входа",
  telegram_notification: "Уведомление в Telegram",
  members_l_display_name: "Отображаемое имя участника",
  base_type: "Тип базы",
  facebook_email: "Email на Facebook",
  secret_pass: "Секретный пароль",
  payment_postcode: "Почтовый индекс плательщика",
  work_profile: "Рабочий профиль",
  "3ds": "3DS",
  exp_date: "Дата истечения",
  relocity_weekly_progress_attachments:
    "Еженедельный прогресс Relocity с вложениями",
  nomer_pfr: "Номер PFR",
  user_phone: "Телефон пользователя",
  block_hours: "Блокированные часы",
  forum_pips: "Forum Pips",
  organ_title: "Название организации",
  advertising_mail_accepted: "Рекламная почта принята",
  lentaViewDate: "Дата просмотра ленты",
  docseria: "Серия документа",
  leader1: "Лидер 1",
  property_form_id: "ID формы свойств",
  listed_count: "Количество в списке",
  spouse_birthday: "День рождения супруга",
  modified_by: "Изменено",
  price_w_disc: "Цена со скидкой",
  sha1: "SHA1",
  ip_country: "Страна IP",
  suspended_at: "Приостановлено в",
  post_office: "Почтовое отделение",
  monitorusercount: "Количество пользователей мониторинга",
  payment_address_format: "Формат адреса оплаты",
  soato: "SOATO",
  payment_option: "Вариант оплаты",
  tg_name: "Имя в Telegram",
  lastMsgTime: "Время последнего сообщения",
  issuing_center: "Центр выдачи",
  avatar: "Аватар",
  u_index: "Индекс пользователя",
  departmentcode: "Код отдела",
  srv: "SRV",
  image_id: "ID изображения",
  information_regulations: "Регулирование информации",
  newlogin: "Новый логин",
  full_name_licensee: "Полное имя лицензиата",
  pm_unread: "PM непрочитанные",
  visa_docs_price_stored: "Цена документов визы",
  contract: "Контракт",
  year_of_manufacture: "Год производства",
  table: "Таблица",
  last_view: "Последний просмотр",
  ip_login_two_fas: "Логин IP с двухфакторной аутентификацией",
  reput_minus: "Минус репутации",
  birthissued_by: "Рождение выдано",
  operation_date: "Дата операции",
  actionStatus: "Статус действия",
  commentary: "Комментарий",
  user_activation_type: "Тип активации пользователя",
  user_country: "Страна пользователя",
  cited: "Цитировано",
  bonuspay: "Бонусный платеж",
  vip_fio: "VIP ФИО",
  insurance_reported: "Страхование сообщено",
  last_booking: "Последняя бронь",
  customer_id: "ID клиента",
  addition2: "Дополнение 2",
  orderCurrency: "Валюта заказа",
  esiaid: "ESIA ID",
  addErrorMsg: "Добавить сообщение об ошибке",
  driver_id: "ID водителя",
  utm_source: "UTM источник",
  telegram_chat_id: "ID чата Telegram",
  contact_fax: "Контактный факс",
  oid: "OID",
  members_disable_pm: "Члены отключили личные сообщения",
  documents: "Документы",
  ein: "EIN",
  index_ufps_to_ccode: "Индекс UFPS для CCode",
  driver_licence: "Водительское удостоверение",
  date_modified: "Дата изменения",
  date_cancelled: "Дата отмены",
  relocity_occupancy_type: "Тип занятости Relocity",
  gpg_name: "Имя GPG",
  operator_price_rub: "Цена оператора в рублях",
  information_cancellation: "Информация об отмене",
  purchase_doc_date: "Дата покупного документа",
  payerCurrency: "Валюта плательщика",
  staff_dat_in: "Дата входа сотрудников",
  sort: "Сортировать",
  registered_at: "Зарегистрирован на",
  body_no: "Номер кузова",
  work_state: "Рабочий штат",
  remarks: "Замечания",
  comission: "Комиссия",
  deletedat: "Удалено на",
  protected: "Защищенный",
  secondary_group_ids: "ID вторичных групп",
  shipping_postcode: "Почтовый индекс доставки",
  pepactivate: "PEP-активация",
  work_zip: "Рабочий ZIP-код",
  identityIssuer: "Исполнитель идентификации",
  partner_first_visited_at: "Партнер посетил впервые на",
  departmentCode: "Код отдела",
  corpus: "Корпус",
  kpp_ccode: "KPP-код",
  operator_price_usd: "Цена оператора в USD",
  issuedate: "Дата выдачи",
  followers: "Подписчики",
  last_order_date: "Дата последнего заказа",
  real_address: "Реальный адрес",
  shipping_zone_id: "ID зоны доставки",
  partner_loyalty_program_card_number:
    "Номер карты программы лояльности партнера",
  f_house_id: "ID дома",
  viewed: "Просмотрено",
  site_id: "ID сайта",
  gps_s: "GPS-s",
  invited_by_user_profile: "Профиль пользователя, который пригласил",
  polis_date: "Дата полиса",
  sa_import_dat: "SA-дата импорта",
  forwarded_ip: "IP перенаправления",
  confirmed_orders_count: "Количество подтвержденных заказов",
  other_information: "Другая информация",
  shipping_address_format: "Формат адреса доставки",
  work_address: "Рабочий адрес",
  bik: "БИК",
  vu_given_date: "Дата выдачи ВУ",
  "twitter.id": "ID Twitter",
  reset_password_sent_at: "Время отправления запроса на сброс пароля",
  latestschedulebooking: "Последнее записанное расписание",
  addr_other: "Другой адрес",
  address_city: "Город проживания",
  back_webmoney_wmid: "Webmoney WMID",
  is_deleted: "Удалено",
  ga_purchase_tracked: "Отслеживание покупок GA",
  work_position_2: "Должность 2",
  saie: "SAIE",
  "twitter.imgUrl": "URL изображения Twitter",
  shipping_address_1: "Адрес доставки 1",
  docnomer: "Номер документа",
  PTS_date: "Дата PTS",
  sms_currency: "Валюта SMS",
  dateExpire: "Дата истечения",
  personal_www: "Личный WWW",
  polis: "Полис",
  uuid_protection: "Защита UUID",
  antispy_subscription: "Подписка на антишпионаж",
  patronymic_1: "Отчество 1",
  build: "Строение",
  doc_type: "Тип документа",
  agreed_at: "Дата согласия",
  forum_last: "Последний форум",
  work_pager: "Рабочий пейджер",
  user_group_id: "ID группы пользователя",
  back_card_number: "Номер карты",
  address_region: "Регион проживания",
  "vkontakte.nickName": "Никнейм VKontakte",
  rating: "Рейтинг",
  retired_at: "Дата ухода на пенсию",
  service: "Сервис",
  back_user_wmp: "Пользователь WMP",
  was_confirmed: "Подтверждено",
  yahoo: "Yahoo",
  calls_count: "Количество звонков",
  weatlas: "Weatlas",
  hp_power: "Мощность двигателя",
  expire_year: "Год истечения",
  real_name: "Настоящее имя",
  clientstatus_ccode: "Код статуса клиента",
  "ЛИТЕРА КВАРТИРЫ": "Литера квартиры",
  u_house_id: "ID дома",
  statuses_count: "Количество статусов",
  correction_date: "Дата исправления",
  passport_issued_on: "Дата выдачи паспорта",
  send_failures_count: "Количество неудачных отправок",
  relevance: "Релевантность",
  naspunkt: "Наспункт",
  identif_r: "Идентификация",
  medium: "Объем",
  type_of_crime: "Тип преступления",
  disabled_at: "Дата отключения",
  github: "GitHub",
  trophy_points: "Очки достижений",
  tab: "Вкладка",
  is_company: "Является компанией",
  auto_money_amount: "Сумма денег",
  agreements: "Соглашения",
  street2: "Улица 2",
  polis_serie: "Серия полиса",
  industry: "Отрасль",
  buh_email: "Email бухгалтера",
  code_podr: "Код подразделения",
  uldomkv: "Адрес",
  a_group: "Группа А",
  recipient_surname: "Фамилия получателя",
  id_user: "ID пользователя",
  social_type: "Тип социальной сети",
  send_failures_changed: "Изменено количество неудачных отправок",
  internetid: "Internet ID",
  shipping_zone: "Зона доставки",
  last_claimed_at: "Последний заявленный дата",
  nickName: "Псевдоним",
  scheme_id: "ID схемы",
  ngs_id: "NGS ID",
  secret: "Секрет",
  "rozysk-initiator": "Инициатор розыска",
  omnidesk_id: "Omnidesk ID",
  number_booking_last_30: "Количество заказов за последние 30 дней",
  issuer: "Выдающий",
  settlement_to_name: "Наименование получателя платежа",
  opt_in_confirmation: "Подтверждение подписки",
  can_access_closed: "Доступ к закрытым",
  deposit_used: "Использованный депозит",
  prepayment_deadline: "Срок предоплаты",
  reg_document: "Регистрационный документ",
  members_l_username: "Имя пользователя участника",
  auto_money: "Автоматический деньги",
  advcake_trackid: "Advcake TrackID",
  message_count: "Количество сообщений",
  expiration: "Истечение срока",
  ip_address: "IP-адрес",
  want_position: "Желаемая позиция",
  ib_scheme_valid: "IB Scheme Valid",
  platform_family_reg: "Регистрация семейства платформ",
  personal_profession: "Личная профессия",
  PNOMZ: "Номер ОМЗ",
  postalcode: "Почтовый код",
  end_date: "Дата окончания",
  epr_like_given: "EPR Like Given",
  chassis_no: "Номер шасси",
  address_home: "Домашний адрес",
  password3: "Пароль 3",
  recepient_name: "Имя получателя",
  block_date: "Дата блокировки",
  modified: "Изменено",
  gr_weight: "GR вес",
  jabber: "Jabber",
  passport_given_date: "Дата выдачи паспорта",
  INN: "ИНН",
  news_num: "Номер новости",
  cancelation_description: "Описание отмены",
  require_phone_verify: "Требуется проверка телефона",
  utm_campaign: "Utm кампания",
  pts: "PTS",
  address_street: "Улица адреса",
  addition1: "Дополнение 1",
  register_doc_number: "Номер регистрационного документа",
  yalaststatussend: "Yalaststatussend",
  imgUrl: "URL изображения",
  bcrypt: "Bcrypt хэш",
  dat_process: "Дата процесса",
  cashier: "Кассир",
  views: "Просмотры",
  facebook_nickName: "Facebook ник",
  start_date: "Дата начала",
  full_operator_payment_deadline: "Срок полной оплаты оператором",
  loyalty_card_type: "Тип карты лояльности",
  pm_all: "PM All",
  customer: "Клиент",
  back_qiwi_phone: "Back QIWI Phone",
  sv_date: "SV дата",
  unconfirmed_phone: "Неподтвержденный телефон",
  vu_seria: "VU серия",
  kladr: "КЛАДР",
  leader2: "Лидер 2",
  operator_order_url: "URL заказа оператора",
  md5: "MD5",
  insurance_company: "Страховая компания",
  pay_method: "Способ оплаты",
  balances: "Балансы",
  stat_base_price: "Базовая цена статистики",
  work_department: "Рабочий отдел",
  card_mask: "Маска карты",
  account_number: "Номер счета",
  make: "Сделать",
  strkhovoi_nomer: "Страховой номер",
  first_six: "Первые шесть цифр карты",
  photo: "Фото",
  access: "Доступ",
  qr: "QR",
  number_spaces_ever: "Число пробелов всегда",
  smpers_id: "ID Smpers",
  has_sign: "Имеет подпись",
  external_auth_id: "ID внешней аутентификации",
  human_info: "Информация о человеке",
  last_cookie_link: "Последняя ссылка cookie",
  location_id: "ID местоположения",
  places: "Места",
  addition: "Дополнение",
  phone_old: "Старый телефон",
  members_profile_views: "Просмотры профилей участников",
  passport_address: "Адрес паспорта",
  joinedPhones: "Присоединенные телефоны",
  badges: "Значки",
  translator_type: "Тип переводчика",
  system_number: "Системный номер",
  bday_month: "День рождения месяц",
  shipping_description: "Описание доставки",
  passport_issued_at: "Паспорт выдан",
  new_purse_two_fas: "Новый кошелек Two-FAS",
  anketa_type: "Тип анкеты",
  social_status: "Социальный статус",
  unitpayId: "Unitpay ID",
  sum_order: "Сумма заказа",
  visible: "Видимый",
  personal_phone: "Личный телефон",
  pass: "Пароль",
  locality_id: "ID местности",
  referral_balance: "Реферальный баланс",
  purchase_doc: "Документ покупки",
  mera: "Мера",
  count_orders: "Количество заказов",
  unn: "УНН",
  validity: "Действительность",
  sv_number: "Номер СВ",
  phone_work: "Рабочий телефон",
  avatar_date: "Дата аватара",
  org_phone: "Телефон организации",
  last_join: "Последняя присоединенная",
  PlatformFamilyReg: "Platform семейная регистрация",
  unique_jumps: "Уникальные прыжки",
  shipping_name: "Имя доставки",
  series: "Серия",
  page_title: "Заголовок страницы",
  password_salt: "Соль пароля",
  fb_pic: "Картинка FB",
  current_ip: "Текущий IP",
  relocity_total_budgeted: "Relocity всего сохранено",
  forum_rank: "Ранг на форуме",
  document_date: "Дата документа",
  old_sv_number: "Старый номер СВ",
  operator_commission: "Комиссия оператора",
  xf_bdreputation_given: "Выданная репутация",
  bday_year: "Год рождения",
  bonuses_enrolled: "Зачисленные бонусы",
  bx_user_id: "Bx User Id",
  password_hash: "Хеш пароля",
  reg_number: "Регистрационный номер",
  skype_num: "Skype номер",
  registration_notifications_count: "Количество уведомлений о регистрации",
  unique_tourists_count: "Количество уникальных туристов",
  street1: "Улица 1",
  yataxi_status: "Статус Yataxi",
  buh_fax: "Факс бухгалтера",
  back_user_wmr: "Вернуть пользователя WMR",
  profile_image_url_https: "URL изображения профиля (HTTPS)",
  want_type_name: "Желаемый тип имени",
  karta_pn: "Карта ПН",
  friend_count: "Количество друзей",
  personal_icq: "Личный ICQ",
  FirstSessionDay: "Первый день сессии",
  scheme_valid: "Схема действительна",
  companies: "Компании",
  confirmed_at: "Подтверждено в",
  passport_issue: "Выдача паспорта",
  recurrent: "Повторяющийся",
  organ_name: "Название организации",
  last_punishment: "Последнее наказание",
  work_company: "Рабочая компания",
  utm_medium: "UTM медиум",
  work_www: "Рабочий WWW",
  nds_number: "Номер НДС",
  card_data: "Данные карты",
  loginip: "IP входа",
  register_code: "Регистрационный код",
  recommend_level: "Уровень рекомендации",
  back_user_wmz: "Вернуть пользователя WMZ",
  number_spaces_last_30: "Количество пробелов за последние 30 дней",
  os_family: "Семейство ОС",
  name_1: "Имя 1",
  user_group: "Группа пользователей",
  owner: "Владелец",
  back_yd_account_id: "Вернуть YD account ID",
  unconfirmed_email: "Неподтвержденный email",
  count_rides: "Количество поездок",
  billing_id: "ID биллинга",
  countries_visited_count: "Количество посещенных стран",
  googleid: "Google ID",
  payer_address: "Адрес плательщика",
  auto_time_zone: "Автоматический часовой пояс",
  remote_control_number: "Номер пульта",
  sales_date: "Дата продажи",
  purchase_time: "Время покупки",
  flight_number: "Номер рейса",
  departure_date: "Дата вылета",
  departure_time: "Время вылета",
  seat: "Место",
  departure_point: "Отправление",
  boarding_point1: "Посадка1",
  boarding_point2: "Посадка2",
  boarding_point3: "Посадка3",
  vc_sale: "VC_SALE",
  vc_take: "VC_TAKE",
  cashier_id: "Идентиф. № кассира",
  ticket_sale_date: "Дата продажи билета",
  ticket_sale_time: "Время продажи билета",
  departure_station: "Станция отправления",
  arrival_station: "Станция назначения",
  arrival_date: "Дата прибытия",
  arrival_time: "Время прибытия",
  train_number: "Номер поезда",
  wagon_number: "Номер вагона",
  seat_count: "Количество мест",
  ticket_form: "Форма проездных документов",
  seat_type: "Тип места",
  passenger_document_number_and_name: "Номер документа и ФИО пассажира",
  seat_number: "Номер места",
  airline: "Авиакомпания",
  arrival_airport: "Аэропорт прибытия",
  passenger_info: "Информация о пассажире",
  fio: "ФИО пассажира",
  flight_date: "Дата рейса",
  flight_time: "Время рейса",
  departure_airport: "Аэропорт вылета",
  destination_airport: "Аэропорт назначения",
  operation_type: "Тип операции",
  issuing_authority: "Орган, выдавший ИД",
  date_of_issue: "Дата выдачи ИД",
  content_of_ID: "Содержание ИД",
  bailiff_name: "ФИО пристава",
  territorial_department: "Территориальный отдел",
  npt: "Населенный пункт",
  telephone: "Телефон",
  activation_date: "Дата активации",
  withdrawal_date: "Дата отключения",
  product_status: "Статус продукта",
  technology: "Технология",
  band_technology: "Технология доступа",
  client_name: "Имя клиента",
  client_type: "Тип клиента",
  address_type: "Тип адреса",
  address_complement: "Дополнение к адресу",
  postal_code: "Почтовый индекс",
  landline_contact: "Домашний телефон",
  neighborhood: "Район",
  svfl: "Сведения о физическом лице",
  innfl: "Индивидуальный номер налогоплательщика физического лица",
  ogrnip:
    "Основной государственный регистрационный номер индивидуального предпринимателя",
  datavyp: "Дата выдачи документа",
  svgrazhd: "Сведения о гражданстве",
  svokved: "Сведения о классификаторе видов экономической деятельности",
  svregip: "Сведения о регистрации индивидуального предпринимателя",
  svregpf: "Сведения о регистрации в пенсионном фонде",
  kodvidip: "Код вида индивидуального предпринимателя",
  svregorg: "Сведения о регистрирующем органе",
  svuchetno: "Сведения об учете в налоговом органе",
  naimvidip: "Наименование вида индивидуального предпринимателя",
  svprekrashch: "Сведения о прекращении деятельности",
  dataogrnip: "Дата присвоения огрнип",
  svzapegrip:
    "Сведения о записи в егрип (единый государственный реестр индивидуальных предпринимателей)",
  pol: "Пол человека",
  fiorus: "Фио на русском языке",
  grnipdata:
    "Данные о дате регистрации и грнип (основного государственного регистрационного номера индивидуального предпринимателя)",
  imia: "Имя человека",
  familiia: "Фамилия человека",
  otchestvo: "Отчество человека",
  grnip: "Главный регистрационный номер индивидуального предпринимателя",
  datazapisi: "Дата записи",
  vidgrazhd: "Вид гражданства",
  svokveddop:
    "Сведения об дополнительных классификаторах видов экономической деятельности",
  svokvedosn:
    "Сведения об основном классификаторе видов экономической деятельности",
  kodokved: "Код классификатора видов экономической деятельности",
  naimokved: "Наименование классификатора видов экономической деятельности",
  regnom: "Регистрационный номер",
  datareg: "Дата регистрации",
  svorgpf: "Сведения о регистрации в пенсионном фонде организации",
  regnompf: "Регистрационный номер в пенсионном фонде",
  kodpf: "Код пенсионного фонда",
  naimpf: "Наименование пенсионного фонда",
  adrro: "Адрес регистрации организации",
  kodno: "Код налогового органа",
  naimno: "Наименование налогового органа",
  svno: "Сведения об учете в налоговом органе",
  datapostuch: "Дата постановки на учет",
  svstatus: "Сведения о статусе записи",
  kodstatus: "Код статуса",
  naimstatus: "Наименование статуса",
  dataprekrashch: "Дата прекращения",
  idzap: "Идентификатор записи",
  vidzap: "Вид записи",
  svsvid: "Сведения о документе, удостоверяющем личность",
  datazap: "Дата записи",
  svedpreddok: "Сведения о предоставленном документе",
  kodspvz: "Код способа внесения записи",
  naimvidzap: "Наименование вида записи",
  nomer: "Номер документа",
  seriia: "Серия документа",
  datavydsvid: "Дата выдачи свидетельства",
  nomdok: "Номер документа",
  naimdok: "Наименование документа",
  datadok: "Дата документа",
  lastactive: "Последняя активность",
  lastname_2: "Фамилия",
  uf_region: "Регион",
  diagnosis_2: "Диагноз",
  google: "Google",
  postnum: "Почтовый индекс",
  shipmentStore: "Магазин отгрузки",
  client_comment: "Комментарий клиента",
  free_chest_ip: "Свободный IP-адрес",
  educations: "Образование",
  free_day_times: "Свободное время в день",
  customerComment: "Комментарий клиента",
  passworddate: "Дата пароля",
  shipped: "Отправлено",
  firstname_2: "Имя",
  friendreqcount: "Количество запросов в друзья",
  is_hd_skin: "HD-скин",
  postcode: "Почтовый индекс",
  timezoneoffset: "Смещение часового пояса",
  enforcement_proceedings: "Исполнительное производство",
  internal_country: "Внутренняя страна",
  date_created: "Дата создания",
  mult_chest_can: "Мульти-грудная клетка",
  bonusesCreditTotal: "Всего бонусов кредита",
  input_date: "Дата ввода",
  registration_location: "Место регистрации",
  unbans: "Разбаны",
  slug: "Слаг",
  delivery: "Доставка",
  joindate: "Дата вступления",
  purchase_date: "Дата покупки",
  payments: "Платежи",
  contragent: "Контрагент",
  threadnum: "Номер треда",
  final_diagnosis: "Конечный диагноз",
  profile_visits: "Просмотры профиля",
  vkontakte_id: "ID Вконтакте",
  medpolis_number: "Номер Медполиса",
  Помещение: "Помещение",
  name1: "Название",
  illness: "Болезнь",
  qiwi: "Qiwi",
  additional_educations: "Дополнительное образование",
  recovery: "Восстановление",
  timezone_offset: "Смещение часового пояса",
  engine_type: "Тип двигателя",
  mileage: "Пробег",
  steering_wheel: "Руль",
  secUid: "SecUid",
  work_site: "Рабочий сайт",
  pm_total: "Всего личных сообщений",
  manager_comment: "Комментарий менеджера",
  pmtotal: "Всего личных сообщений",
  orderMethod: "Метод заказа",
  barcode: "Штрих-код",
  is_hd_cape: "HD-накидка",
  lastvisit: "Последний визит",
  childrens_count: "Количество детей",
  items: "Элементы",
  dislikes_received: "Получено дизлайков",
  course_number: "Номер курса",
  mobile: "Мобильный телефон",
  user_spec: "Спецификация пользователя",
  profile_pic: "Фотография профиля",
  pastes: "Вставки",
  founder: "Основатель",
  join_timestamp: "Метка времени подключения",
  externalId: "Внешний ID",
  sitename: "Название сайта",
  doctor: "Доктор",
  ufworkpost: "Рабочий пост",
  logindate: "Дата входа",
  goods: "Товары",
  payeer: "Payeer",
  exchange: "Обмен",
  contact: "Контакт",
  Bday1: "День рождения",
  appartment: "Квартира",
  alcoholconsumption: "Потребление алкоголя",
  privilegeType: "Тип привилегии",
  calltime: "Время звонка",
  modification: "Модификация",
  orderType: "Тип заказа",
  moderation: "Модерация",
  fee: "Комиссия",
  ufspec: "Спецификация",
  nompsp: "Номер ПСП",
  likesreceived: "Получено лайков",
  locality: "Населенный пункт",
  reputation: "Репутация",
  linkedinid: "ID LinkedIn",
  documentofenforcementproceedings: "Документ исполнительного производства",
  direction: "Направление",
  summ: "Сумма",
  internalregion: "Внутренний регион",
  driveunit: "Привод",
  outcome: "Результат",
  datetime: "Дата и время",
  ufcountry: "Страна",
  document2: "Документ",
  passwords: "Пароли",
  purchaselocation: "Место покупки",
  subdivisionoffssp: "Подразделение ФССП",
  friendsrequestcount: "Количество запросов в друзья",
  customFields: "Пользовательские поля",
  purchaseSumm: "Сумма покупки",
  lastfreechest: "Последняя свободная грудная клетка",
  classnumber: "Номер класса",
  phonecontact: "Контактный телефон",
  userid: "ID пользователя",
  borndate: "Дата рождения",
  lastpost: "Последнее сообщение",
  internaltimezone: "Внутренний часовой пояс",
  expired: "Срок действия истек",
  ufworkposition: "Рабочая позиция",
  destination: "Место назначения",
  personalsite: "Личный сайт",
  prepaySum: "Сумма предоплаты",
  friendcount: "Количество друзей",
  totalSumm: "Общая сумма",
  message: "Сообщение",
  countryIso: "ISO страны",
  personal: "Жизненная позиция",
  political: "Политические предпочтения",
  people_main: "Главное в людях",
  life_main: "Главное в жизни",
  smoking: "Отношение к курению",
  alcohol: "Отношение к алкоголю",
  langs: "Языки",
  year_from: "Год начала",
  year_to: "Год окончания",
  year_graduated: "Год выпуска",
  relatives: "Родственники",
  schools: "Школы",
  universities: "Университеты",
  occupation: "Работа",
  uuid_sberbank: "UUID Сбербанк",
  country_of_study: "Страна обучения",
  type_of_educational_institution: "Тип учебного заведения",
  course: "Курс",
  municipal_entity: "Муниципальное образование",
  institution_name: "Название учебного заведения",
  quote: "Цитата",
  who_access_mult: "Доступ для множества",
  twitter_name: "Имя в Twitter",
  has_googleid: "Имеет Google ID",
  reject_message: "Сообщение об отказе",
  client_notes: "Заметки клиента",
  price_delivery: "Стоимость доставки",
  imsi: "IMSI",
  registered_complaints: "Зарегистрированные жалобы",
  online_pay_transaction: "Онлайн-платежная транзакция",
  telecom_operator_region: "Регион оператора связи",
  the_your_code: "Ваш код",
  verification_code: "Код верификации",
  priority_ticket: "Приоритетный билет",
  all_price: "Общая цена",
  free_last_date: "Дата последнего бесплатного дня",
  system_products_unloaded: "Выгруженные продукты системы",
  registerDate: "Дата регистрации",
  cluster_level2: "Уровень кластера 2",
  appointments_notify_by_email:
    "Уведомления о назначениях по электронной почте",
  shipping_address: "Адрес доставки",
  idfromcrm: "ID из CRM",
  class_code: "Код класса",
  idorgfromcrm: "ID организации из CRM",
  parent_email: "Email родителя",
  job_city: "Город работы",
  linkedin_id: "ID в LinkedIn",
  medpolis_date: "Дата медицинской полисной страховки",
  brnch_branch_id: "ID филиала",
  receiving_home: "Получение на дом",
  learning_language: "Язык обучения",
  research_date: "Дата исследования",
  fullname_lat: "ФИО латиницей",
  pts_owners_count: "Количество владельцев ПТС",
  phone_contact: "Телефон для контакта",
  vacation_ends_at: "Дата окончания отпуска",
  health_group: "Группа здоровья",
  education_document: "Документ об образовании",
  school_code: "Код школы",
  apartment: "Квартира",
  certificate_amount_total: "Общая сумма сертификата",
  cluster_level3: "Уровень кластера 3",
  imei: "IMEI",
  login_date: "Дата входа",
  date_future_delivery: "Дата будущей доставки",
  level: "Уровень",
  date_end: "Дата окончания",
  movement_details: "Детали движения",
  desired_work_schedule: "Желаемый график работы",
  name2: "Имя 2",
  parent_gemotest_id: "ID родительского Gemotest",
  operator_code: "Код оператора",
  doit: "Сделать",
  time_branch_client: "Время в филиале клиента",
  municipality_name: "Название муниципалитета",
  free_fast_chest: "Бесплатное быстрое хранение",
  is_poor_family: "Бедная семья",
  os_name: "Имя ОС",
  area_area_id: "ID области",
  zone_id: "ID зоны",
  gubern: "Губернатор",
  research_result: "Результат исследования",
  storeName: "Название магазина",
  datetime_future_delivery: "Дата и время будущей доставки",
  verification_code_can_use: "Код верификации",
  search_title: "Название поиска",
  receiving_address: "Адрес получения",
  certificate_amount_type: "Тип суммы сертификата",
  dscnt_discount_id: "ID скидки",
  disability_group: "Группа инвалидности",
  comp_specialization: "Специализация компании",
  structure: "Структура",
  share_analyzes: "Делиться анализами",
  sbis_id: "ID SBIS",
  uf_workpost: "Рабочее место UF",
  courses: "Курсы",
  registration_fullname: "Полное имя при регистрации",
  assumed_position: "Предполагаемая должность",
  serial_sim: "Серийный SIM",
  start_time: "Время начала",
  following: "Следующий",
  school_class: "Класс в школе",
  from_language: "Из какого языка",
  debt_amount: "Сумма долга",
  cluster: "Кластер",
  job_profiling_result: "Результат профилирования работы",
  settlement: "Поселение",
  uf_country: "Страна UF",
  assigned_person: "Назначенное лицо",
  school_class_profile: "Профиль класса в школе",
  additional_contacts: "Дополнительные контакты",
  sso_email: "Email SSO",
  date_start: "Дата начала",
  school_title: "Название школы",
  item: "Элемент",
  profile_name: "Имя профиля",
  public_organization: "Общественная организация",
  intelligence_id: "ID интеллекта",
  roles: "Роли",
  communication: "Связь",
  rural_council: "Сельский совет",
  hobby: "Хобби",
  last_free_chest: "Последний бесплатный ящик",
  esia_id: "ID ЕСИА",
  duration: "Продолжительность",
  division: "Подразделение",
  foreignLanguage: "Иностранный язык",
  paid_total: "Всего оплачено",
  fullname_user: "Полное имя пользователя",
  rso_info: "Информация RSO",
  time_future_delivery: "Время будущей доставки",
  facebook_data: "Данные Facebook",
  diagnosis_1: "Диагноз 1",
  class_letter: "Буква класса",
  on_avito_from: "На Avito из",
  home_page: "Домашняя страница",
  gplus_name: "Имя в Google Plus",
  delivery_method: "Метод доставки",
  the_create_goodness: "Создание добра",
  gemotest_id: "ID Gemotest",
  contacts: "Контакты",
  internal_time_zone: "Внутренняя временная зона",
  class_number: "Номер класса",
  apteka: "Аптека",
  date_of_registration: "Дата регистрации",
  distance_branch_client: "Удаленность филиала клиента",
  health_limitation: "Ограничения по здоровью",
  born_date: "Дата рождения",
  address_title: "Название адреса",
  auth_count: "Количество аутентификаций",
  name_lat: "Имя (латиницей)",
  oms: "ОМС (Обязательное медицинское страхование)",
  flying_with: "Лететь с",
  yandex_reviews_link: "Ссылка на отзывы в Yandex",
  minimum_salary: "Минимальная зарплата",
  percentage_discount: "Процентная скидка",
  date_time: "Дата и время",
  document_2: "Документ 2",
  nomsac: "Номер нормативно-справочного акта",
  fullname_norm: "Полное имя (нормативное)",
  hd_can: "Может HD",
  client: "Клиент",
  appointments_notify_by_phone: "Уведомления о назначениях по телефону",
  receiving_street: "Улица получения",
  frontpad_id: "ID Frontpad",
  receiving_room: "Комната получения",
  insurance_number: "Номер страховки",
  role_in_event: "Роль в событии",
  is_appointments_notification_manage_enabled:
    "Включено управление уведомлениями о назначениях",
  organization_id: "ID организации",
  city_id: "ID города",
  dislikes_given: "Выставленные дизлайки",
  experiences: "Опыт",
  post_count: "Количество постов",
  additional_privileges: "Дополнительные привилегии",
  is_rso: "Является RSO",
  lastvisitDate: "Дата последнего посещения",
  connection_date: "Дата подключения",
  works_in_organization_id: "Работает в организации с ID",
  job_vacancy: "Вакансия",
  consulting_cost: "Стоимость консультации",
  code_or_intercom: "Код или домофон",
  introduce_yourself: "Представьтесь",
  hd_forever: "Вечная HD",
  medicaments: "Лекарства",
  family_size: "Размер семьи",
  client_discount: "Скидка клиента",
  count_persons: "Количество лиц",
  recommendations: "Рекомендации",
  solution: "Решение",
  orgns_organizations_id: "ID организации (orgns)",
  shipping_fullname: "Полное имя получателя",
  password_date: "Дата пароля",
  clothesSize: "Размер одежды",
  address_2: "Адрес 2",
  diamonds: "Бриллианты",
  receiving_level: "Уровень получения",
  total_price: "Общая стоимость",
  purchase_location: "Место покупки",
  immunization_date: "Дата вакцинации",
  lоgin: "Логин",
  overdue: "Просрочено",
  research_name: "Название исследования",
  avatar_url: "URL аватара",
  telecom_operator: "Телеком-оператор",
  purchase_price: "Стоимость покупки",
  the_call: "Вызов",
  is_young_army: "Является молодым солдатом",
  omnichat_id: "ID Omnichat",
  buslik_id: "ID Buslik",
  converge_soc: "Социальные сети Converge",
  home: "Домашний адрес",
  price_products: "Цена продуктов",
  bailiff_department: "Отдел судебных приставов",
  job_facility: "Место работы",
  partner: "Партнёр",
  all_on_board: "Все на борту",
  call_time: "Время звонка",
  events: "События",
  gplus_uid: "UID в Google Plus",
  passport_info: "Информация о паспорте",
  streak: "Полоса",
  phone3: "Телефон 3",
  patronymic_lat: "Отчество (латиницей)",
  is_gto: "Является GTO",
  research_validity: "Срок действия исследования",
  patient_age_group: "Возрастная группа пациента",
  alcohol_consumption: "Потребление алкоголя",
  yandex_public_id: "Публичный ID в Yandex",
  flight_signature: "Подпись полета",
  vacation_starts_at: "Начало отпуска",
  is_large_family: "Является многодетной семьей",
  school: "Школа",
  last_visit_date: "Дата последнего посещения",
  Bday_1: "День рождения 1",
  old_address: "Прежний адрес",
  comment_client: "Комментарий клиента",
  internal_region: "Внутренний регион",
  sberbank_acquiring_id: "ID приобретения Сбербанка",
  datetime_delivered: "Дата и время доставки",
  job_processing_history: "История обработки рабочих задач",
  upload_products: "Загрузить продукты",
  userwho: "Пользователь, который",
  has_fbid: "Имеет Facebook ID",
  comp_post: "Должность в компании",
  school_number: "Номер школы",
  other_org_info: "Другая информация об организации",
  flights: "Рейсы",
  gto_info: "Информация о GTO",
  acquiring_title: "Название приобретения",
  last_visited_at: "Последнее посещение",
  research_rus_name: "Русское название исследования",
  receiving_method: "Метод получения",
  motivation: "Мотивация",
  bank_payment_number: "Номер банковского платежа",
  purchase_price_with_discount: "Цена покупки с учетом скидки",
  phone2: "Телефон",
  status_pay: "Статус оплаты",
  reason_failed: "Причина неудачи",
  incident_date: "Дата инцидента",
  your_vector: "Ваш вектор",
  store_number: "Номер магазина",
  parent_fullname: "ФИО родителя",
  is_new_card: "Новая карта",
  sms_1_hour: "SMS за 1 час",
  site_name: "Название сайта",
  tickets: "Билеты",
  sale_price: "Цена продажи",
  friends_request_count: "Количество запросов в друзья",
  measurement_unit: "Единица измерения",
  store_code: "Код магазина",
  birth_certificate: "Свидетельство о рождении",
  doctor_conclusion: "Заключение врача",
  stop_time: "Время остановки",
  author: "Автор",
  school_book: "Школьная книга",
  time_left: "Оставшееся время",
  role_in_contest: "Роль в конкурсе",
  address_text: "Текст адреса",
  cluster_level1: "Уровень кластера 1",
  likes_received: "Полученные лайки",
  user_type: "Тип пользователя",
  ip_date: "Дата IP",
  expert: "Эксперт",
  address_metro: "Метро адреса",
  drive_unit: "Дисковая единица",
  os_version: "Версия ОС",
  growth: "Рост",
  client_instagram: "Instagram клиента",
  verification_code_sended_at: "Время отправки кода верификации",
  bday_text: "Текст дня рождения",
  has_plus: "Имеет Plus",
  appearance: "Внешность",
  usertitle: "Заголовок пользователя",
  schoolclass_id: "ID школьного класса",
  thread_count: "Количество веток",
  specialty_id: "ID специальности",
  email_2: "Email 2",
  caller_type: "Тип вызывающего",
  last_vote_notifer: "Последний уведомитель о голосовании",
  created_by_id: "Создано пользователем с ID",
  gplus_data: "Данные Google Plus",
  IIN: "ИИН (Индивидуальный идентификационный номер)",
  has_phone: "Имеет телефон",
  young_army_info: "Информация о молодежной армии",
  research_category: "Категория исследования",
  parent_phone: "Телефон родителя",
  surname_lat: "Фамилия (латиницей)",
  total: "Итого",
  birtday: "День рождения",
  total_xp: "Общий опыт",
  your_choice: "Ваш выбор",
  paid_rub: "Оплачено (рубли)",
  class: "Класс",
  works_from: "Работает с",
  allowance: "Пособие",
  sso_region: "Регион SSO",
  uf_spec: "Специальность UF",
  likes_given: "Данные лайки",
  represents: "Представляет",
  twitter_data: "Данные Twitter",
  intercom: "Домофон",
  personal_site: "Личный сайт",
  area_area_id1: "ID области",
  research_contragent: "Контрагент исследования",
  fast_chest: "Быстрый ящик",
  team_race: "Гонка команд",
  lead_path: "Путь лидера",
  user_title: "Заголовок пользователя",
  uf_work_position: "Должность UF",
};
